[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/static/media/*.woff2"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

    # Multi-value headers are expressed with multi-line strings.
	cache-control = '''
    public,
	max-age=60,
	immutable'''