[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/static/media/*.woff2"
  [headers.values]
	cache-control = '''
    public,
	max-age=3600,
	immutable'''

[build]
  command = "npm run build"
  functions = "handleJoin"
  publish = "functions"
