openapi: 3.0.3
info:
  title: Club Connect - Brooklyn College Computer Science Club
  description: The public API documentation for Club Connect, the full-stack portal for the Brooklyn College Computer Science Club.
  version: 1.0.0
servers:
  - url: 'http://127.0.0.1:8080'
tags:
  - name: root
    description: Base routes for the application.
  - name: account
    description: Routes regarding authentication with the application.
  - name: announcements
    description: Routes regarding club announcements for registered club members.
  - name: events
    description: Routes regarding club events.
components:
  securitySchemes:
    jwtCookieAuth:
      type: apiKey
      in: cookie
      name: token
paths:
  # Root
  /:
    get:
      summary: Checks whether or not the server is working.
      tags:
        - root
      responses:
        200:
          description: The server has acknowledged your request and is working properly.
  # Accounts
  /accounts/login:
    post:
      summary: Logs a member in and returns a JWT to authenticate with the application.
      tags:
        - account
      responses:
        200:
          description: The login was successful. A JWT is returned that can be used with the application to access authenticated routes.
  /accounts/ping:
    get:
      summary: Checks if an issued JWT is valid and ready for authentication with the application.
      tags:
        - account
      responses:
        200:
          description: The JWT is valid and can be used to access restricted routes the member has access to.
  /announcements:
    get:
      summary: Returns a list of announcements.
      description: Requires the Member, BrooklynCollegeMember, or Admin role.
      tags:
        - announcements
      security:
        - jwtCookieAuth: []
      parameters:
        - name: role
          in: query
          description: When provided, return only announcements pertaining to a specific minimum role.
          required: false
          schema:
            type: string
            enum:
              - Member
              - BrooklynCollegeMember

      responses:
        200:
          description: A JSON array of announcements. By default, returns all announcements the authenticated member has access to.<br>If a role was provided, returns only announcements that match the role.
        401:
          description: The member is not authenticated
        403:
          description: The member does not have access/role is not high enough
        404:
          description: The queried role was not found
  /announcements/:id:
    get:
      summary: Gets an announcement by its ID.
      description: Requires the Member, BrooklynCollegeMember, or Admin role.
      tags:
        - announcements
      security:
        - jwtCookieAuth: []
      responses:
        200:
          description: A JSON object with the details of the requested announcement.
          content:
            application/json:
              schema:
                type: object
        401:
          description: The member is not authenticated.
        403:
          description: The member does not have access and/or the member's role is not high enough.
        404:
          description: The queried role was not found.
  /events:
    get:
      summary: Returns a list of events.
      tags:
        - events
      responses:
        200:
          description: A JSON array of events.
          content:
            application/json:
              schema:
                type: array
  /events/{id}:
    get:
      summary: Gets an event by its ID.
      tags:
        - events
      parameters:
        - name: id
          in: path
          description: Event ID
          required: true
          schema:
            type: integer
      responses:
        200:
          description: A JSON object containing event data.
          content:
            application/json:
              schema:
                type: object
        404:
          description: No event was found with the ID.